# Generated by Django 4.2.3 on 2023-07-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In progress', 'In Progress'), ('Completed', 'Completed')], max_length=20),
        ),
    ]
