# Generated by Django 4.2.3 on 2023-07-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_comment_user_alter_task_assigned_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('M', 'Manager'), ('R', 'Regular')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('IP', 'In progress'), ('C', 'Completed')], default='N', max_length=2),
        ),
    ]
