# Generated by Django 4.2.4 on 2023-08-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DFS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UP', 'Unprocessed'), ('P', 'Processing'), ('On way', 'On the Way'), ('D', 'Delivered')], default='unprocessed', max_length=20),
        ),
    ]
